import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
// import styles from '../styles/Home.module.css';
import { useAccount, useBalance } from "wagmi";
import { formatUnits, parseUnits } from "viem";
import Header from "./../components/Header";
import Info from "../components/Info";
import NetworkSwitcher from "../components/Switch";

const Home: NextPage = () => {
  // const account = useAccount();
  // const {data, error} = useBalance({
  //   address: account.address
  // })
  // console.log(data)
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>RainbowKit App</title>
  //       <meta
  //         content="Generated by @rainbow-me/create-rainbowkit"
  //         name="description"
  //       />
  //       <link href="/favicon.ico" rel="icon" />
  //     </Head>
  //     <Header/>

  //     <main className={styles.main}>
  //       <ConnectButton />
  //       <div>address: {account.address}</div>
  //       <div>addresses:{account.addresses}</div>
  //       <div>chainId:{account.chainId}</div>
  //       <div>balance:{data?.formatted}</div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
  //         Made with ❤️ by your frens at 🌈
  //       </a>
  //     </footer>
  //   </div>
  // );

  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <main>
        <Info />
        <NetworkSwitcher />
      </main>
    </>
  );
};

export default Home;
